Candidate.destroy_all
Answer.destroy_all
Quote.destroy_all

c1 = Candidate.create(name:"Kirsten Gillibrand", party: "Democrat")
c2 = Candidate.create(name:"Corey Booker", party: "Democrat")
c3 = Candidate.create(name:"Bernie Sanders", party: "Democrat")
c4 = Candidate.create(name:"Elizabeth Warren", party: "Democrat")
c5 = Candidate.create(name:"Bill DeBlasio", party:"Democrat")
c6 = Candidate.create(name:"Pete Buttigieg",party: "Democrat")
c7 = Candidate.create(name:"Kamala Harris", party:"Democrat")
c8 = Candidate.create(name:"John Kasich", party:"Republican")
c9 = Candidate.create(name:"Donald Trump", party:"Republican")
c10 = Candidate.create(name:"Joe Biden", party:"Democratic")

q1 = Quote.create(isFav: 0, content:"Why should male legislators across this country decide when you are having children, how many and under what circumstances?")
q2 = Quote.create(isFav: 0, content:"The greatest natural resource our country has is not oil. It's not gas. It's not coal. It's the genius of our children.")
q3 = Quote.create(isFav: 0, content:"Democratic socialism means that we must create an economy that works for all, not just the very wealthy.")
q4 = Quote.create(isFav: 0, content:"Maybe you didn't know but I am the creates. To quote the poet Lil' Kim, 'I know you heard me on the radio.'")
q5 = Quote.create(isFav: 0, content:"So @realDonaldTrump, who will be left to do all of that 'side work' at your country club?")
q6 = Quote.create(isFav: 0, content:"We have had excellent presidents who have been young. We have had excellent presidents who have been liberal. I would imagine we’ve probably had excellent presidents who were gay — we just didn’t know which ones")
q7 = Quote.create(isFav: 0, content:"Our campaign is powered by regular folks pitching in a few dollars at a time. We’re not taking a dime from corporate PACs or federal lobbyists. That’s why I’m asking, can you chip in $5 today?")
q8 = Quote.create(isFav: 0, content:"Border security is important, but both sides should be willing to negotiate on how we do it.")
q9 = Quote.create(isFav: 0, content:"In the end, you’re measured not by how much you undertake but by what you finally accomplish.")
q10 = Quote.create(isFav: 0, content:"Sometimes by losing a battle you find a create way to win the war.")
q11 = Quote.create(isFav: 0, content:"If we give Donald Trump eight years in the White House, he will forever and fundamentally alter the character of this nation, who we are, and I cannot stand by and watch that happen")
q12 = Quote.create(isFav: 0, content:"We're putting the people back in charge with more choice for better care at a far lower cost and other people will not be paying for their health care")
q13 = Quote.create(isFav: 0, content:"You cannot go to a 7-11 or a Dunkin' Donuts unless you have a slight Indian accent....I'm not joking.")
q14 = Quote.create(isFav: 0, content:"His mom lived in Long Island for 10 years or so. God rest her soul. And—although, she's—wait—your mom's still—your mom's still alive. Your dad passed. God bless her soul.")
q15 = Quote.create(isFav: 0, content:"I think my positions are going to be what the people in this room come up with.")
q16 = Quote.create(isFav: 0, content:"The past does not have to define the future.") 
q17 = Quote.create(isFav: 0, content:"So please get your asses out tomorrow and vote.")
q18 = Quote.create(isFav: 0, content:"We got more money. We got more brains. We got better houses, apartments. We got nicer boats. We're smarter than they are. And they say, 'The elite.'")
q19 = Quote.create(isFav: 0, content:"Want to get on the front page of the paper? I have to make some vicious attack. I won't do that. I’m running an issue-oriented campaign.")
q20 = Quote.create(isFav: 0, content:"Today's big tech companies have too much power — too much power over our economy, our society, and our democracy. They've bulldozed competition, used our private information for profit, and tilted the playing field against everyone else.")

a1 = Answer.create(quote_id: q1.id, candidate_id: c1.id)
a2 = Answer.create(quote_id: q2.id, candidate_id: c2.id)
a3 = Answer.create(quote_id: q3.id, candidate_id: c3.id)
a4 = Answer.create(quote_id: q4.id, candidate_id: c4.id)
a5 = Answer.create(quote_id: q5.id, candidate_id: c5.id)
a6 = Answer.create(quote_id: q6.id, candidate_id: c6.id)
a7 = Answer.create(quote_id: q7.id, candidate_id: c7.id)
a8 = Answer.create(quote_id: q8.id, candidate_id: c8.id)
a9 = Answer.create(quote_id: q9.id, candidate_id: c9.id)
a10 = Answer.create(quote_id: q10.id, candidate_id: c9.id)
a11 = Answer.create(quote_id: q11.id, candidate_id: c10.id)
a12 = Answer.create(quote_id: q12.id, candidate_id: c9.id)
a13 = Answer.create(quote_id: q13.id, candidate_id: c10.id)
a14 = Answer.create(quote_id: q14.id, candidate_id: c10.id)
a15 = Answer.create(quote_id: q15.id, candidate_id: c9.id)
a16 = Answer.create(quote_id: q16.id, candidate_id: c9.id)
a17 = Answer.create(quote_id: q17.id, candidate_id: c9.id)
a18 = Answer.create(quote_id: q18.id, candidate_id: c9.id)
a19 = Answer.create(quote_id: q19.id, candidate_id: c3.id)
a20 = Answer.create(quote_id: q20.id, candidate_id: c4.id)